---
title: "Locating feeding events"
format: html
editor: source
self-contained: true
---

```{r}
library(targets)
library(tidyverse)
library(here)
library(lubridate)
library(sf)
library(viridis)
library(mapview)
library(ggspatial)
source(here("R/functions.R"))
```

Load carcass placements and feeding bouts
```{r}
# Classified feeding bouts
tar_load(feeding_bouts_station)
fbs24 <- feeding_bouts_station
fbs23 <- readRDS(here("data/ACC/2023_hf_period/created/feeding_bouts_station_2023.RDS"))

fbs <- purrr::list_rbind(fbs24) %>%
  mutate(year = 2024,
         start = lubridate::ymd_hms(start),
         end = lubridate::ymd_hms(end),
         dateOnly = lubridate::ymd(dateOnly)) %>%
  bind_rows(purrr::list_rbind(fbs23) %>%
              mutate(year = 2023,
                     tag_id = as.numeric(tag_id),
                     dateOnly = lubridate::ymd(dateOnly),
                     individual_id = as.numeric(individual_id))) %>%
  sf::st_as_sf(crs = "WGS84") %>%
  sf::st_transform(32636)

length(unique(fbs$device_id)) # 77 individuals are represented now

# Load known carcass placements
tar_load(fs)

# Add carcass IDs
fs <- fs %>%
  mutate(carcass_id = 1:n())
```

Restrict to carcass placements during the time of year
```{r}
max(fs$datetime) # we only have placements through 4/16/24 because of when I requested the data from Gideon. # XXX Write to Gideon and ask for the more up to date data.
# In the meantime, I'll analyze any that occurred during this interval

mindate <- min(fbs$start)
maxdate <- max(fbs$end)

fs_focal <- fs %>% filter(datetime >= mindate, datetime <= maxdate) # we have 404 feeding occurrences.

# Let's see if these individuals fed at these carcasses at all. If not, then I'll need more data for either individuals or carcasses.
```

For each carcass, let's look at feeding bouts within 1000m and 1 day of the carcass.
```{r}
carcass_bouts <- map(1:nrow(fs_focal), ~{
  carcass <- fs_focal[.x,]
  id <- fs_focal$carcass_id[.x]
  distances <- as.numeric(st_distance(fbs, carcass))
  fbs <- fbs %>%
    mutate(carcass_id = id,
           dist_to_carcass = distances)
  keep_distance <- fbs %>%
    filter(dist_to_carcass <= 500)
  keep_time <- keep_distance %>%
    filter(start >= (carcass$datetime - hours(1)), # allow 1 hour before carcass
           end <= (carcass$datetime + hours(24))) %>% # allow 24 hours after carcass
    mutate(time_since_carcass = difftime(start, carcass$datetime, units = "hours"))
  return(keep_time)
}) # only one of these carcasses has a couple feeding bouts. We can look at this for now.
```

```{r}
#map_dbl(carcass_bouts, nrow) # okay, a few of these carcasses now have a bunch of feeding events. Unfortunately, many carcasses still don't have any feeding events.

toinclude <- which(map_dbl(carcass_bouts, nrow) > 0)

# Now let's see how the location of those feeding bouts corresponds to the location of the carcass as recorded by the INPA.

makeplots <- function(fbs, carc, type = "distance"){
  toplot <- bind_rows(carc %>%
                        mutate(type = "carcass"),
                      fbs %>%
                        mutate(type = "feeding_bout"))
  if(type == "time"){
    p <- ggplot(toplot)+
      geom_sf(aes(shape = type, col = time_since_carcass),
              size = 5, alpha = 0.5)+
      scale_color_viridis(name = "Time\nsince carcass", limits = c(-1, 25))+
      scale_shape_manual(name = "", values = c(4, 19))+
      theme_bw()+
      annotation_scale(location = "br")
  }else if(type == "distance"){
    p <- ggplot(toplot)+
      geom_sf(aes(shape = type, col = dist_to_carcass),
              size = 5, alpha = 0.5)+
      scale_color_viridis(name = "Distance\nto carcass", limits = c(0, 100))+
      scale_shape_manual(name = "", values = c(4, 19))+
      theme_bw()+
      annotation_scale(location = "br")
  }else(stop("`type` must be either 'time' or 'distance'"))
  return(p)
}
distanceplots <- map(toinclude, ~{
  makeplots(fbs = carcass_bouts[[.x]], carc = fs_focal[.x,], type = "distance")
})

timeplots <- map(toinclude, ~{
  makeplots(fbs = carcass_bouts[[.x]], carc = fs_focal[.x,], type = "time")
})
```

Let's summarize: how far away are these bouts?
```{r}
all_carcass_bouts <- purrr::list_rbind(carcass_bouts)
all_carcass_bouts %>%
  group_by(carcass_id) %>%
  mutate(mn = mean(dist_to_carcass)) %>%
  ggplot(aes(x = fct_reorder(factor(carcass_id), dist_to_carcass, mean), y = dist_to_carcass, fill = mn))+
  geom_boxplot(outlier.size = 0.5)+
  theme_bw()+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())+
  scale_fill_viridis(name = "Mean distance\nto carcass", limits = c(0, 100))+
  labs(x = "Carcass",
       y = "Distance (m)",
       title = "Distance from feeding bouts to recorded carcass location",
       sutbtitle = "For feeding bouts within 500m",
       caption = "Includes carcasses that had at least 1 feeding bout within 500m.\n Includes feeding bouts from 1 hour before through 24 hours after carcass placement.")
```

Does the distance of the bouts from the carcass change over time?
```{r}
#| warning: false
all_carcass_bouts %>%
  group_by(carcass_id) %>%
  filter(n() > 1) %>%
  ggplot(aes(x = time_since_carcass, y = dist_to_carcass, group = carcass_id))+
  theme_bw()+
  geom_smooth(method = "lm")+
  geom_point(alpha = 0.5, pch = 1)+
  facet_wrap(~carcass_id, scales = "free_x")+
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())+
  labs(y = "Distance (m)",
       x = "Time since carcass placement (hours)",
       caption = "Includes carcasses that had at least 2 feeding bouts within 500m.\n Includes feeding bouts from 1 hour before through 24 hours after carcass placement.")
```

